### ISSUE TITLE
New Gantt : Data Grid Issues

### ISSUE THREAD

**Issue by kalai0103** [visualbis/inforiverdoc#1]
***Build*:**  Name: Gantt Chart (08 Nov 12:54 v1.0.0)
Id: GanttChartF39DAE8D57A743EF89F5C3809DEE2B67_OrgStore
Version: 1.0.0.0

***Steps*:**
 
1. Import Visual 
2. Assign Data Sources -> Required Fields
3. Toolbar -> Data Grid 
4. Make Changes In The Default Settings

***Actual Result* :** 

The Changes Are Not Reflection On The Visual For The Following Options 

Header -> Font Color -> Changes Not Reflecting 

![Image](https://github.com/visualbis/inforiverdoc/assets/49014609/4de3ea55-239d-4e76-9c59-8dbcb30da826)

 Customization -> Root -> Root Node Font Size -> Changes Not Reflecting 

![Image](https://github.com/visualbis/inforiverdoc/assets/49014609/6527e807-19af-45b6-b92a-41ef7d5696f2)

 Customization -> Root -> Root Node Font Size -> Changes Not Reflecting 

![Image](https://github.com/visualbis/inforiverdoc/assets/49014609/7f9df12f-3d92-447d-aada-1aa980aebec9)

***Expected Result* :**

Changes Made In The Data Grid Property Should Be Reflected Properly On The Visual 

https://github.com/visualbis/inforiverdoc/assets/49014609/0b39244c-8810-41c7-a1e0-d380afc249a9

 
***Evidence*** : Please refer to the attached screenshots/Pbix file/video.

**Comment by nsdevaraj** [comment]
https://github.com/visualbis//gantt create under this repository
